exports.data = [
    { "productId": "1", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:05", "updatedAt": "2023-04-12 01:09:05", "categoryId": "1", "brandId": "1" },
    { "productId": "2", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:08", "updatedAt": "2023-04-12 01:09:08", "categoryId": "1", "brandId": "1" },
    { "productId": "3", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:11", "updatedAt": "2023-04-12 01:09:11", "categoryId": "1", "brandId": "1" },
    { "productId": "4", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:14", "updatedAt": "2023-04-12 01:09:14", "categoryId": "1", "brandId": "1" },
    { "productId": "5", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:17", "updatedAt": "2023-04-12 01:09:17", "categoryId": "1", "brandId": "1" },
    { "productId": "6", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:19", "updatedAt": "2023-04-12 01:09:19", "categoryId": "1", "brandId": "1" },
    { "productId": "7", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:22", "updatedAt": "2023-04-12 01:09:22", "categoryId": "1", "brandId": "1" },
    { "productId": "8", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:24", "updatedAt": "2023-04-12 01:09:24", "categoryId": "1", "brandId": "1" },
    { "productId": "9", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:28", "updatedAt": "2023-04-12 01:09:28", "categoryId": "1", "brandId": "1" },
    { "productId": "10", "productName": "hello01332", "productOldPrice": null, "productPrice": "100", "productImage": "https:\/\/www.duocmmo.com\/notice\/access-classroom?status=noLoginToken", "productMadeIn": "hello", "productSaleOff": null, "productSex": null, "productColor": null, "createdAt": "2023-04-12 01:09:30", "updatedAt": "2023-04-12 01:09:30", "categoryId": "1", "brandId": "1" }
]